[package]
name = "fish-printf"
edition = "2021"
version = "0.2.1"
repository = "https://github.com/fish-shell/fish-shell"
description = "printf implementation, based on musl"
license = "MIT"

[dependencies]
libc = "0.2.155"
widestring = { version = "1.0.2", optional = true }
