[package]
name = "fish-util"
edition.workspace = true
rust-version.workspace = true
version = "0.0.0"
repository.workspace = true
license.workspace = true

[dependencies]
fish-widestring.workspace = true
rand.workspace = true

[lints]
workspace = true
