[package]
name = "fish-localization-extraction"
edition.workspace = true
rust-version.workspace = true
version = "0.0.0"
repository.workspace = true
license.workspace = true

[dependencies]
fish-tempfile.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
