[package]
name = "fish-version"
edition.workspace = true
rust-version.workspace = true
version = "0.0.0"
repository.workspace = true

[dependencies]
fish-build-helper.workspace = true

[lints]
workspace = true
