[package]
name = "fish-common"
edition.workspace = true
rust-version.workspace = true
version = "0.0.0"
repository.workspace = true
license.workspace = true

[dependencies]
bitflags.workspace = true
fish-wchar.workspace = true
libc.workspace = true
nix.workspace = true

[lints]
workspace = true
