name: 'Lock threads'

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '365'
          pr-lock-inactive-days: '365'
          issue-exclude-labels: 'question, needs more info'
